x-common-variables:
  read-only-plugin: &read-only-plugin
    # Buildkite containers assume you mount into /plugin
    type: bind
    source: .
    target: /plugin
    read_only: true

services:
  plugin-tester:
    image: buildkite/plugin-tester:v2.0.0
    volumes:
      - *read-only-plugin

  plugin-linter:
    image: buildkite/plugin-linter@sha256:833b1ce8326b038c748c8f04d317045205e115b1732a6842ec4a957f550fe357
    command: ["--id", "grapl-security/vault-login"]
    volumes:
      - *read-only-plugin
