[GLOBAL]
dynamic_ui = false
colors = true

# Since multiple jobs could run on the same Buildkite worker node, we
# need to make sure the cache directories are isolated.
local_store_dir = ".cache/pants/lmdb_store"
named_caches_dir = ".cache/pants/named_caches"

pants_ignore = [
  ".cache/pants/named_caches",
  ".cache/pants/lmdb_store",
]

# Temporarily disable the remote cache until we can get
# repository-specific tokens into the CI/CD system
# [auth]
# from_env_var = "TOOLCHAIN_AUTH_TOKEN"
