---
name: Vault Login
description: Log into a Hashicorp Vault server
author: https://github.com/grapl-security
requirements:
  - "docker"
configuration:
  properties:
    auth_role:
      description: |
        The name of the authentication role to use. If not specified,
        internal (Grapl-specific) logic will be used to generate a
        role name from the Buildkite agent queue name.
      type: string
    image:
      description: |
        The `vault` image to use; defaults to `hashicorp/vault`.
      type: string
    tag:
      description: |
        The `vault` image tag to use; defaults to `latest`.
      type: string
    always-pull:
      description: |
        Explicitly pull the image before running. Useful if using the
        `latest` tag. Defaults to `false`.

        Note that "true", "on", and "1" are all acceptable values to
        enable this option. Any other value is considered synonymous
        with `false`.
      type: boolean
    address:
      description: |
        The address of the Vault server to interact with. Should
        include protocol, server, and port (corresponds to
        'VAULT_ADDR').
      type: string
    namespace:
      description: |
        The Vault namespace to interact with (corresponds to
        'VAULT_NAMESPACE').
      type: string
    attempt_count:
      description: |
        The number of times to attempt to login to Vault before giving
        up. Defaults to 3.
      type: integer
    attempt_wait_seconds:
      description: |
        The number of seconds to wait between each retry
        attempt. Defaults to 5.
      type: integer
    additionalProperties: false
