env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":jeans: All files are covered by Pants"
    command:
      - ./pants tailor --check

  - label: ":lint-roller::bash: Lint Shell"
    command:
      - make lint-shell
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - vault-login-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller::buildkite: Lint Plugin"
    command:
      - make lint-plugin

  - label: ":bash: Unit Test Shell"
    command:
      - make test-shell
    plugins:
      - grapl-security/vault-login#v0.1.2
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - vault-login-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller::buildkite: Test Plugin"
    command:
      - make test-plugin

  - label: ":buildkite::vault: Validate Plugin Behavior"
    command:
      - .buildkite/scripts/environment-hook-validation.sh
    plugins:
      - "grapl-security/vault-login#${BUILDKITE_COMMIT}":
      - improbable-eng/metahook#v0.4.1:
          pre-exit: .buildkite/scripts/pre-exit-hook-validation.sh

  - label: ":buildkite::vault: Validate Plugin Behavior with pull"
    command:
      - .buildkite/scripts/environment-hook-validation.sh
    plugins:
      - "grapl-security/vault-login#${BUILDKITE_COMMIT}":
          always-pull: true
      - improbable-eng/metahook#v0.4.1:
          pre-exit: .buildkite/scripts/pre-exit-hook-validation.sh
